import math

BASELINE_HEIGHT = 600
AREA_WIDTH = 4500

AREA_ANGLE = 5

BASE_EXTENSION = math.tan(AREA_ANGLE * math.pi / 180) * AREA_WIDTH
TOTAL_HEIGHT = BASELINE_HEIGHT + 2 * BASE_EXTENSION

SEARCH_BASE_X = 0
SEARCH_BASE_Y = TOTAL_HEIGHT / 2

TRAVEL_ENTRY_X = AREA_WIDTH + 500
TRAVEL_ENTRY_Y_MIN = 0
TRAVEL_ENTRY_Y_MAX = TOTAL_HEIGHT
